/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Domain.ContentButtons;
import Domain.Friends;
import java.awt.Color;
import java.awt.Point;

/**
 *
 * @author User
 */
public class JFAddFriends extends javax.swing.JFrame {

    private ContentButtons requests;
    private Friends friends;

    /**
     * Creates new form JFFriendRequests
     */
    public JFAddFriends(Friends friends) {

        this.requests = new ContentButtons();
        this.friends = friends;
        fillRequests();
        initComponents();
        this.jtaShowFriends.setText("" + this.requests.getCircularDoublyList().fristInList());
    }

    public void fillRequests() {

        for (int i = 0; i < this.friends.getFriends().size(); i++) {
            this.requests.getCircularDoublyList().addEnd(this.friends.getFriends().get(i).getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitle = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jbtnSearch = new javax.swing.JButton();
        jpIcons = new javax.swing.JPanel();
        jbtnHome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jpFriends = new javax.swing.JPanel();
        jbtnLeft = new javax.swing.JButton();
        jbtnRight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaShowFriends = new javax.swing.JTextArea();
        jBDelete = new javax.swing.JButton();
        jBAccept = new javax.swing.JButton();
        Friends = new javax.swing.JLabel();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitle.setBackground(new java.awt.Color(255, 255, 255));
        jpTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jlTitle.setFont(new java.awt.Font("RTL-Adam Script Heavy", 0, 24)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(0, 0, 0));
        jlTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconImagran02.png"))); // NOI18N

        jbtnSearch.setBackground(new java.awt.Color(255, 255, 255));
        jbtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-lupa-30.png"))); // NOI18N
        jbtnSearch.setToolTipText("search");
        jbtnSearch.setBorder(null);
        jbtnSearch.setBorderPainted(false);

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSearch)
                .addContainerGap(650, Short.MAX_VALUE))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSearch)
                    .addComponent(jlTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        jpIcons.setBackground(new java.awt.Color(255, 255, 255));
        jpIcons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jbtnHome.setBackground(new java.awt.Color(255, 255, 255));
        jbtnHome.setForeground(new java.awt.Color(255, 255, 255));
        jbtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-casa-40.png"))); // NOI18N
        jbtnHome.setToolTipText("home");
        jbtnHome.setBorderPainted(false);
        jbtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomeActionPerformed(evt);
            }
        });

        jbtnAdd.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-bookmark-40.png"))); // NOI18N
        jbtnAdd.setToolTipText("add");
        jbtnAdd.setBorder(null);
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-grupo-de-usuarios-hombre-hombre-40.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIconsLayout = new javax.swing.GroupLayout(jpIcons);
        jpIcons.setLayout(jpIconsLayout);
        jpIconsLayout.setHorizontalGroup(
            jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIconsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIconsLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jpIconsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpIconsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpIconsLayout.setVerticalGroup(
            jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIconsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(jbtnAdd)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        jPanel1.add(jpIcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 70, 540));

        jpFriends.setBackground(new java.awt.Color(255, 255, 255));
        jpFriends.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jbtnLeft.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLeft.setForeground(new java.awt.Color(102, 102, 102));
        jbtnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-izquierda-en-cuadrado-50.png"))); // NOI18N
        jbtnLeft.setToolTipText("left");
        jbtnLeft.setBorderPainted(false);
        jbtnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLeftActionPerformed(evt);
            }
        });

        jbtnRight.setBackground(new java.awt.Color(255, 255, 255));
        jbtnRight.setForeground(new java.awt.Color(102, 102, 102));
        jbtnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-derecha-en-cuadrado-50.png"))); // NOI18N
        jbtnRight.setToolTipText("right");
        jbtnRight.setBorderPainted(false);
        jbtnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRightActionPerformed(evt);
            }
        });

        jtaShowFriends.setEditable(false);
        jtaShowFriends.setBackground(new java.awt.Color(255, 255, 255));
        jtaShowFriends.setColumns(20);
        jtaShowFriends.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtaShowFriends.setForeground(new java.awt.Color(153, 153, 153));
        jtaShowFriends.setRows(5);
        jtaShowFriends.setText("\n");
        jtaShowFriends.setToolTipText("Friends");
        jtaShowFriends.setBorder(null);
        jtaShowFriends.setCaretColor(new java.awt.Color(153, 153, 153));
        jtaShowFriends.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtaShowFriends.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jtaShowFriends.setEnabled(false);
        jtaShowFriends.setRequestFocusEnabled(false);
        jtaShowFriends.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jtaShowFriends);

        jBDelete.setBackground(new java.awt.Color(102, 102, 102));
        jBDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBDelete.setForeground(new java.awt.Color(255, 255, 255));
        jBDelete.setText("Delete");
        jBDelete.setBorder(null);
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBAccept.setBackground(new java.awt.Color(0, 51, 153));
        jBAccept.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBAccept.setForeground(new java.awt.Color(255, 255, 255));
        jBAccept.setText("Accept");
        jBAccept.setBorder(null);
        jBAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAcceptActionPerformed(evt);
            }
        });

        Friends.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Friends.setForeground(new java.awt.Color(0, 0, 102));
        Friends.setText("Friends");

        javax.swing.GroupLayout jpFriendsLayout = new javax.swing.GroupLayout(jpFriends);
        jpFriends.setLayout(jpFriendsLayout);
        jpFriendsLayout.setHorizontalGroup(
            jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFriendsLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(jpFriendsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Friends)
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jpFriendsLayout.setVerticalGroup(
            jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFriendsLayout.createSequentialGroup()
                .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jbtnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Friends)
                        .addGap(31, 31, 31)
                        .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFriendsLayout.createSequentialGroup()
                                .addComponent(jbtnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 720, 540));

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jPanel1.add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLeftActionPerformed

        if (jbtnLeft == evt.getSource()) {

            this.jtaShowFriends.setText("");
            if (this.requests.getCircularDoublyList().isEmpty()) {
                this.jtaShowFriends.setText("");
            } else {
                this.requests.moveLeft();
                this.jtaShowFriends.setText("" + this.requests.getCircularDoublyList().fristInList());
            }
        }
    }//GEN-LAST:event_jbtnLeftActionPerformed

    private void jbtnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRightActionPerformed

        if (jbtnRight == evt.getSource()) {

            this.jtaShowFriends.setText("");
            if (this.requests.getCircularDoublyList().isEmpty()) {
                this.jtaShowFriends.setText("");
            } else {
                this.requests.moveRight();
                this.jtaShowFriends.setText("" + this.requests.getCircularDoublyList().fristInList());
            }
        }
    }//GEN-LAST:event_jbtnRightActionPerformed

    private void jbtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomeActionPerformed
        if (jbtnHome == evt.getSource()) {
            JFFeed jff = new JFFeed(this.friends);
            jff.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnHomeActionPerformed

    private void jBAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAcceptActionPerformed

        if (jBAccept == evt.getSource()) {

            if (this.requests.getCircularDoublyList().getSize() == 1) {
                this.requests.getCircularDoublyList().cancel();
            } else if (this.requests.getCircularDoublyList().getSize() > 1) {
                Object element = this.requests.getCircularDoublyList().fristInList();
                this.requests.getCircularDoublyList().deleteByElement(element);
            }
            if (this.requests.getCircularDoublyList().isEmpty()) {
                this.jtaShowFriends.setText("");
            } else {
                this.jtaShowFriends.setText("" + this.requests.getCircularDoublyList().fristInList());
            }

        }
    }//GEN-LAST:event_jBAcceptActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        if (jBDelete == evt.getSource()) {
            if (this.requests.getCircularDoublyList().getSize() == 1) {
                this.requests.getCircularDoublyList().cancel();
            } else if (this.requests.getCircularDoublyList().getSize() > 1) {
                Object element = this.requests.getCircularDoublyList().fristInList();
                this.requests.getCircularDoublyList().deleteByElement(element);
            }
            if (this.requests.getCircularDoublyList().isEmpty()) {
                this.jtaShowFriends.setText("");
            } else {
                this.jtaShowFriends.setText("" + this.requests.getCircularDoublyList().fristInList());
            }
        }
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFFeed jff = new JFFeed(this.friends);
        jff.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        if (jbtnAdd == evt.getSource()){
        
            JFAddPost jfap = new JFAddPost(this.friends);
            jfap.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Friends;
    private javax.swing.JButton jBAccept;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnHome;
    private javax.swing.JButton jbtnLeft;
    private javax.swing.JButton jbtnRight;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpFriends;
    private javax.swing.JPanel jpIcons;
    private javax.swing.JPanel jpTitle;
    private javax.swing.JTextArea jtaShowFriends;
    // End of variables declaration//GEN-END:variables
}
