/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Domain.ContentButtons;
import Domain.Friends;
import Domain.User;
import Utility.UsuarioXML;
import java.awt.Color;
import java.awt.Point;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdom.JDOMException;

/**
 *
 * @author User
 */
public class JFFriendRequests extends javax.swing.JFrame {

    private ContentButtons buttons;
    private User user;
    private UsuarioXML xML;

    /**
     * Creates new form JFFriendRequests
     */
    public JFFriendRequests(User user) {
        
        try {
            this.user = user;
            this.xML = new UsuarioXML();
            this.buttons = new ContentButtons();

            initComponents();
            if (this.user.getRequest() != null) {
                if (!this.user.getRequest().isEmpty() && this.user.getRequest().fristElement() != null) {
                    this.jtaShowFriends.setText("" + this.user.getRequest().fristElement());
                } else {
                    this.jtaShowFriends.setText("");
                }
            }
        } catch (JDOMException ex) {
            Logger.getLogger(JFFriendRequests.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFFriendRequests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpIcons = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnHome = new javax.swing.JButton();
        jbtnAddPost = new javax.swing.JButton();
        jbtnAddFriends = new javax.swing.JButton();
        jbtnShowFriends = new javax.swing.JButton();
        jbtnLogOut = new javax.swing.JButton();
        jlIconImagran = new javax.swing.JLabel();
        jbtnSearchFriends = new javax.swing.JButton();
        jpFriends = new javax.swing.JPanel();
        jbtnLeft = new javax.swing.JButton();
        jbtnRight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaShowFriends = new javax.swing.JTextArea();
        jBDelete = new javax.swing.JButton();
        jBAccept = new javax.swing.JButton();
        jlFriendsRequest = new javax.swing.JLabel();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(900, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpIcons.setBackground(new java.awt.Color(255, 255, 255));
        jpIcons.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jbtnHome.setBackground(new java.awt.Color(255, 255, 255));
        jbtnHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnHome.setForeground(new java.awt.Color(0, 0, 0));
        jbtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-casa-40_1.png"))); // NOI18N
        jbtnHome.setText("Home     ");
        jbtnHome.setToolTipText("home");
        jbtnHome.setBorder(null);
        jbtnHome.setBorderPainted(false);
        jbtnHome.setFocusPainted(false);
        jbtnHome.setFocusable(false);
        jbtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomeActionPerformed(evt);
            }
        });

        jbtnAddPost.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAddPost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAddPost.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAddPost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-añadir-texto-40.png"))); // NOI18N
        jbtnAddPost.setText("Add Post");
        jbtnAddPost.setToolTipText("AddPost");
        jbtnAddPost.setBorder(null);
        jbtnAddPost.setFocusPainted(false);
        jbtnAddPost.setFocusable(false);
        jbtnAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddPostActionPerformed(evt);
            }
        });

        jbtnAddFriends.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAddFriends.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAddFriends.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAddFriends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-añadir-grupo-de-usuarios-hombre-hombre-40.png"))); // NOI18N
        jbtnAddFriends.setText("Add Friends");
        jbtnAddFriends.setToolTipText("AddFriends");
        jbtnAddFriends.setBorder(null);
        jbtnAddFriends.setFocusPainted(false);
        jbtnAddFriends.setFocusable(false);
        jbtnAddFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddFriendsActionPerformed(evt);
            }
        });

        jbtnShowFriends.setBackground(new java.awt.Color(255, 255, 255));
        jbtnShowFriends.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnShowFriends.setForeground(new java.awt.Color(0, 0, 0));
        jbtnShowFriends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-amigos-40.png"))); // NOI18N
        jbtnShowFriends.setText("Friends");
        jbtnShowFriends.setToolTipText("Friends");
        jbtnShowFriends.setBorder(null);
        jbtnShowFriends.setFocusPainted(false);
        jbtnShowFriends.setFocusable(false);
        jbtnShowFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowFriendsActionPerformed(evt);
            }
        });

        jbtnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-panel-cerrado-40.png"))); // NOI18N
        jbtnLogOut.setToolTipText("Log out");
        jbtnLogOut.setBorder(null);
        jbtnLogOut.setFocusPainted(false);
        jbtnLogOut.setFocusable(false);
        jbtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogOutActionPerformed(evt);
            }
        });

        jlIconImagran.setBackground(new java.awt.Color(255, 255, 255));
        jlIconImagran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-Imagran-panel-Icons.png"))); // NOI18N

        jbtnSearchFriends.setBackground(new java.awt.Color(255, 255, 255));
        jbtnSearchFriends.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnSearchFriends.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSearchFriends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-lupa-35.png"))); // NOI18N
        jbtnSearchFriends.setText("Search \nfriends");
        jbtnSearchFriends.setToolTipText("SearchFriends");
        jbtnSearchFriends.setBorder(null);
        jbtnSearchFriends.setFocusPainted(false);
        jbtnSearchFriends.setFocusable(false);
        jbtnSearchFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchFriendsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIconsLayout = new javax.swing.GroupLayout(jpIcons);
        jpIcons.setLayout(jpIconsLayout);
        jpIconsLayout.setHorizontalGroup(
            jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIconsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIconsLayout.createSequentialGroup()
                        .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(jpIconsLayout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnAddPost)
                                    .addComponent(jbtnAddFriends)
                                    .addComponent(jbtnShowFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13))
                    .addGroup(jpIconsLayout.createSequentialGroup()
                        .addComponent(jbtnLogOut)
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIconsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlIconImagran, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnSearchFriends, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jpIconsLayout.setVerticalGroup(
            jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIconsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlIconImagran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAddFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnShowFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSearchFriends)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jbtnLogOut)
                .addContainerGap())
        );

        jPanel1.add(jpIcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 680));

        jpFriends.setBackground(new java.awt.Color(255, 255, 255));
        jpFriends.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jbtnLeft.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLeft.setForeground(new java.awt.Color(102, 102, 102));
        jbtnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-izquierda-en-cuadrado-50.png"))); // NOI18N
        jbtnLeft.setToolTipText("left");
        jbtnLeft.setBorderPainted(false);
        jbtnLeft.setFocusPainted(false);
        jbtnLeft.setFocusable(false);
        jbtnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLeftActionPerformed(evt);
            }
        });

        jbtnRight.setBackground(new java.awt.Color(255, 255, 255));
        jbtnRight.setForeground(new java.awt.Color(102, 102, 102));
        jbtnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-derecha-en-cuadrado-50.png"))); // NOI18N
        jbtnRight.setToolTipText("right");
        jbtnRight.setBorderPainted(false);
        jbtnRight.setFocusPainted(false);
        jbtnRight.setFocusable(false);
        jbtnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRightActionPerformed(evt);
            }
        });

        jtaShowFriends.setEditable(false);
        jtaShowFriends.setBackground(new java.awt.Color(255, 255, 255));
        jtaShowFriends.setColumns(20);
        jtaShowFriends.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtaShowFriends.setForeground(new java.awt.Color(51, 51, 51));
        jtaShowFriends.setRows(5);
        jtaShowFriends.setText(" Se hace con colas");
        jtaShowFriends.setToolTipText("Friends");
        jtaShowFriends.setBorder(null);
        jtaShowFriends.setCaretColor(new java.awt.Color(153, 153, 153));
        jtaShowFriends.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtaShowFriends.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jtaShowFriends.setEnabled(false);
        jtaShowFriends.setFocusable(false);
        jtaShowFriends.setRequestFocusEnabled(false);
        jtaShowFriends.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtaShowFriends.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jtaShowFriends);

        jBDelete.setBackground(new java.awt.Color(204, 204, 204));
        jBDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBDelete.setForeground(new java.awt.Color(0, 0, 0));
        jBDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-basura-30.png"))); // NOI18N
        jBDelete.setText("Delete");
        jBDelete.setToolTipText("Delete");
        jBDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jBDelete.setBorderPainted(false);
        jBDelete.setFocusPainted(false);
        jBDelete.setFocusable(false);
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBAccept.setBackground(new java.awt.Color(204, 204, 204));
        jBAccept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBAccept.setForeground(new java.awt.Color(0, 0, 0));
        jBAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-lleno-más-2-matemáticas-30.png"))); // NOI18N
        jBAccept.setText("Add Friend");
        jBAccept.setToolTipText("AddFriend");
        jBAccept.setBorder(null);
        jBAccept.setBorderPainted(false);
        jBAccept.setFocusPainted(false);
        jBAccept.setFocusable(false);
        jBAccept.setMaximumSize(new java.awt.Dimension(76, 32));
        jBAccept.setMinimumSize(new java.awt.Dimension(76, 32));
        jBAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAcceptActionPerformed(evt);
            }
        });

        jlFriendsRequest.setBackground(new java.awt.Color(255, 255, 255));
        jlFriendsRequest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlFriendsRequest.setForeground(new java.awt.Color(0, 0, 0));
        jlFriendsRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_friendsRequests.png"))); // NOI18N
        jlFriendsRequest.setToolTipText("");

        javax.swing.GroupLayout jpFriendsLayout = new javax.swing.GroupLayout(jpFriends);
        jpFriends.setLayout(jpFriendsLayout);
        jpFriendsLayout.setHorizontalGroup(
            jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFriendsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFriendsRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFriendsLayout.createSequentialGroup()
                                .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jBAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jpFriendsLayout.setVerticalGroup(
            jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFriendsLayout.createSequentialGroup()
                .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jbtnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jlFriendsRequest)
                        .addGap(28, 28, 28)
                        .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFriendsLayout.createSequentialGroup()
                                .addComponent(jbtnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)))))
                .addGap(18, 18, 18)
                .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jPanel1.add(jpFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 720, 680));

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fondo imagran.png"))); // NOI18N
        jPanel1.add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLeftActionPerformed

        if (jbtnLeft == evt.getSource()) {
            this.jtaShowFriends.setText("");
            this.buttons.moveLeftRequests(this.user.getRequest());
            if (this.user.getRequest() != null) {
                if (!this.user.getRequest().isEmpty() && this.user.getRequest().fristElement() != null) {
                    this.jtaShowFriends.setText("" + this.user.getRequest().fristElement());
                } else {
                    this.jtaShowFriends.setText("");
                }
            }
        }
    }//GEN-LAST:event_jbtnLeftActionPerformed

    private void jbtnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRightActionPerformed

        if (jbtnRight == evt.getSource()) {
            this.jtaShowFriends.setText("");
            this.buttons.moveRightRequests(this.user.getRequest());
            if (this.user.getRequest() != null) {
                if (!this.user.getRequest().isEmpty() && this.user.getRequest().fristElement() != null) {
                    this.jtaShowFriends.setText("" + this.user.getRequest().fristElement());
                } else {
                    this.jtaShowFriends.setText("");
                }
            }
        }
    }//GEN-LAST:event_jbtnRightActionPerformed

    private void jBAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAcceptActionPerformed

        if (jBAccept == evt.getSource()) {

           
            if (this.user.getRequest().getSize() == 1) {
                String element = (String) this.user.getRequest().fristElement();
                this.xML.addFriends(user, element);
                this.xML.actualizarRequests(element, user);
                this.user.getRequest().cancel();
            } else if (this.user.getRequest().getSize() > 1) {
                String element = (String) this.user.getRequest().fristElement();
                this.xML.addFriends(user, element);
                this.xML.actualizarRequests(element, user);
                this.user.getRequest().delete();
            }
            if (this.user.getRequest().isEmpty()) {
                this.jtaShowFriends.setText("");
            } else {
                this.jtaShowFriends.setText("" + this.user.getRequest().fristElement());
            }
        }
    }//GEN-LAST:event_jBAcceptActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        if (jBDelete == evt.getSource()) {
            if (this.user.getRequest().getSize() == 1) {
                String element = (String) this.user.getRequest().fristElement();

                this.xML.actualizarRequests(element, user);
                this.user.getRequest().cancel();
            } else if (this.user.getRequest().getSize() > 1) {
                String element = (String) this.user.getRequest().fristElement();

                this.xML.actualizarRequests(element, user);

                this.user.getRequest().delete();
            }
            if (this.user.getRequest().isEmpty()) {
                this.jtaShowFriends.setText("");
            } else {
                this.jtaShowFriends.setText("" + this.user.getRequest().fristElement());
            }
        }
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jbtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomeActionPerformed
        if (jbtnHome == evt.getSource()) {
            JFFeed jff = new JFFeed(this.user);
            jff.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnHomeActionPerformed

    private void jbtnAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddPostActionPerformed
        if (jbtnAddPost == evt.getSource()){
            JFAddPost jfap = new JFAddPost(this.user);
            jfap.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnAddPostActionPerformed

    private void jbtnAddFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddFriendsActionPerformed
        JFFriendRequests jff = new JFFriendRequests(this.user);
        jff.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnAddFriendsActionPerformed

    private void jbtnShowFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowFriendsActionPerformed
        if (jbtnShowFriends == evt.getSource()){
            JFShowFriends jfap = new JFShowFriends(this.user);
            jfap.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnShowFriendsActionPerformed

    private void jbtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogOutActionPerformed
        if (jbtnLogOut == evt.getSource()){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnLogOutActionPerformed

    private void jbtnSearchFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchFriendsActionPerformed
                if (this.jbtnSearchFriends == evt.getSource()) {
            JFSearchFriends jfSF = new JFSearchFriends(this.user);
            jfSF.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnSearchFriendsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFriendRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFriendRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFriendRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFriendRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAccept;
    private javax.swing.JButton jBDelete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnAddFriends;
    private javax.swing.JButton jbtnAddPost;
    private javax.swing.JButton jbtnHome;
    private javax.swing.JButton jbtnLeft;
    private javax.swing.JButton jbtnLogOut;
    private javax.swing.JButton jbtnRight;
    private javax.swing.JButton jbtnSearchFriends;
    private javax.swing.JButton jbtnShowFriends;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlFriendsRequest;
    private javax.swing.JLabel jlIconImagran;
    private javax.swing.JPanel jpFriends;
    private javax.swing.JPanel jpIcons;
    private javax.swing.JTextArea jtaShowFriends;
    // End of variables declaration//GEN-END:variables
}
