/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Domain.ContentButtons;
import Domain.Friends;
import Domain.User;
import Logic.CircularDoublyList;

/**
 *
 * @author User
 */
public class JFShowFriends extends javax.swing.JFrame {

    private ContentButtons buttons;
    private User user;

    /**
     * Creates new form JFFriendRequests
     */
    public JFShowFriends(User user) {
        this.user = user;
        this.buttons = new ContentButtons();
        initComponents();
        if (this.user.getFriends() == null || this.user.getFriends().isEmpty()) {
            this.jtaShowFriends.setText("");
        } else {
            User u = (User) this.user.getFriends().fristInList();
            this.jtaShowFriends.setText("" + u.getUser());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpIcons = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnHome = new javax.swing.JButton();
        jbtnAddPost = new javax.swing.JButton();
        jbtnAddFriends = new javax.swing.JButton();
        jbtnShowFriends = new javax.swing.JButton();
        jbtnLogOut = new javax.swing.JButton();
        jlIconImagran = new javax.swing.JLabel();
        jbtnSearchFriends = new javax.swing.JButton();
        jpFriends = new javax.swing.JPanel();
        jbtnLeft = new javax.swing.JButton();
        jbtnRight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaShowFriends = new javax.swing.JTextArea();
        Friends = new javax.swing.JLabel();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpIcons.setBackground(new java.awt.Color(255, 255, 255));
        jpIcons.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jbtnHome.setBackground(new java.awt.Color(255, 255, 255));
        jbtnHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnHome.setForeground(new java.awt.Color(0, 0, 0));
        jbtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-casa-40_1.png"))); // NOI18N
        jbtnHome.setText("Home     ");
        jbtnHome.setToolTipText("home");
        jbtnHome.setBorderPainted(false);
        jbtnHome.setFocusPainted(false);
        jbtnHome.setFocusable(false);
        jbtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomeActionPerformed(evt);
            }
        });

        jbtnAddPost.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAddPost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAddPost.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAddPost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-añadir-texto-40.png"))); // NOI18N
        jbtnAddPost.setText("Add Post");
        jbtnAddPost.setToolTipText("add");
        jbtnAddPost.setBorder(null);
        jbtnAddPost.setFocusPainted(false);
        jbtnAddPost.setFocusable(false);
        jbtnAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddPostActionPerformed(evt);
            }
        });

        jbtnAddFriends.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAddFriends.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAddFriends.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAddFriends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-añadir-grupo-de-usuarios-hombre-hombre-40.png"))); // NOI18N
        jbtnAddFriends.setText("Add Friends");
        jbtnAddFriends.setToolTipText("AddFriends");
        jbtnAddFriends.setBorder(null);
        jbtnAddFriends.setFocusPainted(false);
        jbtnAddFriends.setFocusable(false);
        jbtnAddFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddFriendsActionPerformed(evt);
            }
        });

        jbtnShowFriends.setBackground(new java.awt.Color(255, 255, 255));
        jbtnShowFriends.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnShowFriends.setForeground(new java.awt.Color(0, 0, 0));
        jbtnShowFriends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-amigos-40.png"))); // NOI18N
        jbtnShowFriends.setText("Friends");
        jbtnShowFriends.setToolTipText("Friends");
        jbtnShowFriends.setBorder(null);
        jbtnShowFriends.setFocusPainted(false);
        jbtnShowFriends.setFocusable(false);
        jbtnShowFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowFriendsActionPerformed(evt);
            }
        });

        jbtnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-panel-cerrado-40.png"))); // NOI18N
        jbtnLogOut.setToolTipText("Log out");
        jbtnLogOut.setBorder(null);
        jbtnLogOut.setFocusPainted(false);
        jbtnLogOut.setFocusable(false);
        jbtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogOutActionPerformed(evt);
            }
        });

        jlIconImagran.setBackground(new java.awt.Color(255, 255, 255));
        jlIconImagran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-Imagran-panel-Icons.png"))); // NOI18N

        jbtnSearchFriends.setBackground(new java.awt.Color(255, 255, 255));
        jbtnSearchFriends.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnSearchFriends.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSearchFriends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-lupa-35.png"))); // NOI18N
        jbtnSearchFriends.setText("Search \nfriends");
        jbtnSearchFriends.setToolTipText("SearchFriends");
        jbtnSearchFriends.setBorder(null);
        jbtnSearchFriends.setFocusPainted(false);
        jbtnSearchFriends.setFocusable(false);
        jbtnSearchFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchFriendsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIconsLayout = new javax.swing.GroupLayout(jpIcons);
        jpIcons.setLayout(jpIconsLayout);
        jpIconsLayout.setHorizontalGroup(
            jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIconsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIconsLayout.createSequentialGroup()
                        .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(jpIconsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlIconImagran)
                                .addGap(7, 7, 7)))
                        .addGap(11, 11, 11))
                    .addGroup(jpIconsLayout.createSequentialGroup()
                        .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnLogOut)
                            .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtnHome)
                                .addGroup(jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnAddPost)
                                    .addComponent(jbtnAddFriends)
                                    .addComponent(jbtnShowFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnSearchFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpIconsLayout.setVerticalGroup(
            jpIconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIconsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlIconImagran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAddFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnShowFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSearchFriends)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jbtnLogOut)
                .addContainerGap())
        );

        jPanel1.add(jpIcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 680));

        jpFriends.setBackground(new java.awt.Color(255, 255, 255));
        jpFriends.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jbtnLeft.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLeft.setForeground(new java.awt.Color(102, 102, 102));
        jbtnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-izquierda-en-cuadrado-50.png"))); // NOI18N
        jbtnLeft.setToolTipText("left");
        jbtnLeft.setBorderPainted(false);
        jbtnLeft.setFocusPainted(false);
        jbtnLeft.setFocusable(false);
        jbtnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLeftActionPerformed(evt);
            }
        });

        jbtnRight.setBackground(new java.awt.Color(255, 255, 255));
        jbtnRight.setForeground(new java.awt.Color(102, 102, 102));
        jbtnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-derecha-en-cuadrado-50.png"))); // NOI18N
        jbtnRight.setToolTipText("right");
        jbtnRight.setBorderPainted(false);
        jbtnRight.setFocusPainted(false);
        jbtnRight.setFocusable(false);
        jbtnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRightActionPerformed(evt);
            }
        });

        jtaShowFriends.setEditable(false);
        jtaShowFriends.setBackground(new java.awt.Color(255, 255, 255));
        jtaShowFriends.setColumns(20);
        jtaShowFriends.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtaShowFriends.setForeground(new java.awt.Color(51, 51, 51));
        jtaShowFriends.setRows(5);
        jtaShowFriends.setText("\n");
        jtaShowFriends.setToolTipText("Friends");
        jtaShowFriends.setBorder(null);
        jtaShowFriends.setCaretColor(new java.awt.Color(255, 255, 255));
        jtaShowFriends.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtaShowFriends.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jtaShowFriends.setEnabled(false);
        jtaShowFriends.setFocusable(false);
        jtaShowFriends.setRequestFocusEnabled(false);
        jtaShowFriends.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jtaShowFriends);

        Friends.setBackground(new java.awt.Color(255, 255, 255));
        Friends.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Friends.setForeground(new java.awt.Color(255, 255, 255));
        Friends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-AllFriends.png"))); // NOI18N

        javax.swing.GroupLayout jpFriendsLayout = new javax.swing.GroupLayout(jpFriends);
        jpFriends.setLayout(jpFriendsLayout);
        jpFriendsLayout.setHorizontalGroup(
            jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFriendsLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jbtnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addComponent(Friends)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
        jpFriendsLayout.setVerticalGroup(
            jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFriendsLayout.createSequentialGroup()
                .addGroup(jpFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jbtnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jbtnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFriendsLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Friends, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jPanel1.add(jpFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 720, 680));

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fondo imagran.png"))); // NOI18N
        jPanel1.add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLeftActionPerformed

        if (jbtnLeft == evt.getSource()) {
            if (this.user.getFriends() != null) {

                this.jtaShowFriends.setText("");
                if (this.user.getFriends().isEmpty()) {
                    this.jtaShowFriends.setText("");
                } else {
                    this.buttons.moveDown(this.user.getFriends());
                    User u = (User) this.user.getFriends().fristInList();
                    this.jtaShowFriends.setText("" + u.getUser());
                }
            }
        }
    }//GEN-LAST:event_jbtnLeftActionPerformed

    private void jbtnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRightActionPerformed

        if (jbtnRight == evt.getSource()) {
            if (this.user.getFriends() != null) {
                this.jtaShowFriends.setText("");
                if (this.user.getFriends().isEmpty()) {
                    this.jtaShowFriends.setText("");
                } else {
                    this.buttons.moveUp(this.user.getFriends());
                    User u = (User) this.user.getFriends().fristInList();
                    this.jtaShowFriends.setText("" + u.getUser());
                }
            }

        }

    }//GEN-LAST:event_jbtnRightActionPerformed

    private void jbtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomeActionPerformed
        if (jbtnHome == evt.getSource()) {
            JFFeed jff = new JFFeed(this.user);
            jff.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnHomeActionPerformed

    private void jbtnAddFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddFriendsActionPerformed
        JFFriendRequests jff = new JFFriendRequests(this.user);
        jff.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnAddFriendsActionPerformed

    private void jbtnAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddPostActionPerformed
        if (jbtnAddPost == evt.getSource()) {
            JFAddPost jfap = new JFAddPost(this.user);
            jfap.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnAddPostActionPerformed

    private void jbtnShowFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowFriendsActionPerformed
        if (jbtnShowFriends == evt.getSource()) {
            JFShowFriends jfap = new JFShowFriends(this.user);
            jfap.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnShowFriendsActionPerformed

    private void jbtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogOutActionPerformed
        if (jbtnLogOut == evt.getSource()) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnLogOutActionPerformed

    private void jbtnSearchFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchFriendsActionPerformed
        if (this.jbtnSearchFriends == evt.getSource()) {
            JFSearchFriends jfSF = new JFSearchFriends(user);
            jfSF.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnSearchFriendsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFShowFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFShowFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFShowFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFShowFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Friends;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnAddFriends;
    private javax.swing.JButton jbtnAddPost;
    private javax.swing.JButton jbtnHome;
    private javax.swing.JButton jbtnLeft;
    private javax.swing.JButton jbtnLogOut;
    private javax.swing.JButton jbtnRight;
    private javax.swing.JButton jbtnSearchFriends;
    private javax.swing.JButton jbtnShowFriends;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlIconImagran;
    private javax.swing.JPanel jpFriends;
    private javax.swing.JPanel jpIcons;
    private javax.swing.JTextArea jtaShowFriends;
    // End of variables declaration//GEN-END:variables
}
